-- liquibase formatted sql

-- changeset Redmibook14:1717845186770-1
CREATE TABLE app_order
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_station_id INTEGER                                  NOT NULL,
    to_station_id   INTEGER                                  NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status          SMALLINT                                 NOT NULL,
    user_id         INTEGER                                  NOT NULL,
    CONSTRAINT pk_app_order PRIMARY KEY (id)
);

-- changeset Redmibook14:1717845186770-2
CREATE TABLE station
(
    station_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    station    VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_station PRIMARY KEY (station_id)
);

-- changeset Redmibook14:1717845186770-3
ALTER TABLE app_order
    ADD CONSTRAINT FK_APP_ORDER_ON_FROM_STATION FOREIGN KEY (from_station_id) REFERENCES station (station_id);

-- changeset Redmibook14:1717845186770-4
ALTER TABLE app_order
    ADD CONSTRAINT FK_APP_ORDER_ON_TO_STATION FOREIGN KEY (to_station_id) REFERENCES station (station_id);

